PRAGMA foreign_keys = ON;

CREATE TABLE folders(
	ID INTEGER NOT NULL,
	name VARCHAR(40) NOT NULL,
	parentID VARCHAR(40) NOT NULL,
	favorited INTEGER,
	static INTEGER,
	PRIMARY KEY(ID),
	FOREIGN KEY(parentID) REFERENCES folders(ID) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE applications(
	ID INTEGER NOT NULL,
	name VARCHAR(40) NOT NULL,
	folderID VARCHAR(40) NOT NULL,
	invocation VARCHAR(1024),
        icon VARCHAR(500),
	favorited INTEGER,
	PRIMARY KEY(ID),
	CONSTRAINT appnames UNIQUE(name),
	FOREIGN KEY(folderID) REFERENCES folders(ID) ON DELETE CASCADE
);

