PRAGMA foreign_keys = ON;

CREATE TABLE folders(
	ID INTEGER NOT NULL,
	name VARCHAR(40) NOT NULL,
	parentID INTEGER NOT NULL,
	favorited INTEGER,
	static integer,
	PRIMARY KEY(ID),
	CONSTRAINT foldernames UNIQUE(name),
	FOREIGN KEY(parentID) REFERENCES folders(ID) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE applications(
	ID INTEGER NOT NULL,
	name VARCHAR(40) NOT NULL,
	description VARCHAR(1024),
	favorited INTEGER,
	CONSTRAINT appnames UNIQUE(name),
	PRIMARY KEY(ID)
);

CREATE TABLE filed(
	folderID INTEGER NOT NULL,
	appID INTEGER NOT NULL,
	PRIMARY KEY (folderID, appID),
	FOREIGN KEY (folderID) REFERENCES folders(ID) ON DELETE CASCADE,
	FOREIGN KEY (appID) REFERENCES applications(ID) ON DELETE CASCADE,
	CONSTRAINT singlefiled UNIQUE(appID)
);

